### ISSUE TITLE
Realidad Aumentada

### ISSUE THREAD

**Issue by Joel343** [SistemasTecTlaxiaco/infografia-Joel343#1]
[REALIDAD.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Joel343/files/8054312/REALIDAD.pdf)

**Comment by claudiasilvavenda** [comment]
La infografía cumple con lo que pide la rubrica.
la calif. es 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
