### ISSUE TITLE
Infografia ingenieria de software

### ISSUE THREAD

**Issue by Joel343** [SistemasTecTlaxiaco/infografia-Joel343#3]
[conceptos basicos de ingenieria de software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Joel343/files/6186552/conceptos.basicos.de.ingenieria.de.software.pdf)

**Comment by Jaimer117** [comment]
Calificación.  20

**Comment by josealfredo79** [comment]
Este trabajo no esta completo debe especificar las fases de la ingeniería de requisitos y su aplicación

**Comment by Joel343** [comment]
[conceptos basicos de ingenieria de software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Joel343/files/6186564/conceptos.basicos.de.ingenieria.de.software.pdf)

**Comment by Joel343** [comment]
[conceptos basicos de ingenieria de software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Joel343/files/6186567/conceptos.basicos.de.ingenieria.de.software.pdf)

**Comment by josealfredo79** [comment]
Esta revisado y corregido

**Comment by Joel343** [comment]
Gracias ing.
